/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービス死活監視 (ClusterIP 内部のみ) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開中のお知らせ一覧を返す (gateway 経由でクライアントに届く) */
        get: operations["listAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/announcements/{announcementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ID 指定でお知らせ詳細を返す (期間外・下書きでも返す) */
        get: operations["getAnnouncement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        AnnouncementListResponse: {
            announcements: components["schemas"]["AnnouncementSummary"][];
        };
        /**
         * @description `GET /api/v1/support/announcements` のレスポンス要素。
         *     expires_at / body はクライアントに露出させない。
         */
        AnnouncementSummary: {
            /** Format: int64 */
            announcement_id: number;
            type: components["schemas"]["AnnouncementType"];
            title: string;
            /** Format: date-time */
            published_at: string;
        };
        /**
         * @description `GET /api/v1/support/announcements/{announcementId}` のレスポンス。
         *     published_at は下書きの場合 null、expires_at はクライアントに露出させない。
         */
        AnnouncementDetail: {
            /** Format: int64 */
            announcement_id: number;
            type: components["schemas"]["AnnouncementType"];
            title: string;
            body: string;
            /** Format: date-time */
            published_at: string | null;
        };
        /**
         * @description お知らせ種別。
         * @enum {string}
         */
        AnnouncementType: "info" | "maintenance" | "event" | "update";
    };
    responses: never;
    parameters: {
        AnnouncementIdPath: number;
        /**
         * @description 取得言語。許容値は domain.SupportedLangs と同期する
         *     (drift 検知は本ファイルでは行わず application 層で `IsSupportedLang` が担う)。
         */
        LangQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listAnnouncements: {
        parameters: {
            query: {
                /**
                 * @description 取得言語。許容値は domain.SupportedLangs と同期する
                 *     (drift 検知は本ファイルでは行わず application 層で `IsSupportedLang` が担う)。
                 */
                lang: components["parameters"]["LangQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description お知らせ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementListResponse"];
                };
            };
            /** @description lang 未指定 / 非対応 lang */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAnnouncement: {
        parameters: {
            query: {
                /**
                 * @description 取得言語。許容値は domain.SupportedLangs と同期する
                 *     (drift 検知は本ファイルでは行わず application 層で `IsSupportedLang` が担う)。
                 */
                lang: components["parameters"]["LangQuery"];
            };
            header?: never;
            path: {
                announcementId: components["parameters"]["AnnouncementIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description お知らせ詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementDetail"];
                };
            };
            /** @description lang 未指定 / 非対応 lang */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 該当お知らせ無し / 指定 lang の翻訳無し */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
