// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apisupport

import (
	"time"
)

// AnnouncementSummary は `GET /internal/v1/announcements` のレスポンス要素 (FEATURE_SPEC §4)。
// expires_at / body はクライアントに露出させない。
type AnnouncementSummary struct {
	AnnouncementID int64     `json:"announcement_id"`
	Type           string    `json:"type"`
	Title          string    `json:"title"`
	PublishedAt    time.Time `json:"published_at"`
}

// AnnouncementListResponse は `GET /internal/v1/announcements` のトップレベル JSON。
type AnnouncementListResponse struct {
	Announcements []AnnouncementSummary `json:"announcements"`
}

// AnnouncementDetail は `GET /internal/v1/announcements/:id` のレスポンス (FEATURE_SPEC §5)。
// published_at は下書きの場合 null、expires_at はクライアントに露出させない。
type AnnouncementDetail struct {
	AnnouncementID int64      `json:"announcement_id"`
	Type           string     `json:"type"`
	Title          string     `json:"title"`
	Body           string     `json:"body"`
	PublishedAt    *time.Time `json:"published_at"`
}

