// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apisupport

// SubmitInquiryRequest は `POST /api/v1/inquiries` の入力 (FEATURE_SPEC §7.1)。
type SubmitInquiryRequest struct {
	Title      string `json:"title"`
	Body       string `json:"body"`
	ReplyEmail string `json:"reply_email"`
}

// SubmitInquiryResponse は `POST /api/v1/inquiries` の出力。
type SubmitInquiryResponse struct {
	InquiryID int64 `json:"inquiry_id"`
}

