// Package apisupport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apisupport

import (
	"time"
)

// Defines values for AnnouncementType.
const (
	AnnouncementTypeEvent       AnnouncementType = "event"
	AnnouncementTypeInfo        AnnouncementType = "info"
	AnnouncementTypeMaintenance AnnouncementType = "maintenance"
	AnnouncementTypeUpdate      AnnouncementType = "update"
)

// Valid indicates whether the value is a known member of the AnnouncementType enum.
func (e AnnouncementType) Valid() bool {
	switch e {
	case AnnouncementTypeEvent:
		return true
	case AnnouncementTypeInfo:
		return true
	case AnnouncementTypeMaintenance:
		return true
	case AnnouncementTypeUpdate:
		return true
	default:
		return false
	}
}

// AnnouncementDetail `GET /api/v1/support/announcements/{announcementId}` のレスポンス (FEATURE_SPEC §5)。
// published_at は下書きの場合 null、expires_at はクライアントに露出させない。
type AnnouncementDetail struct {
	AnnouncementID int64      `json:"announcement_id"`
	Body           string     `json:"body"`
	PublishedAt    *time.Time `json:"published_at"`
	Title          string     `json:"title"`

	// Type お知らせ種別 (FEATURE_SPEC §2)。
	Type AnnouncementType `json:"type"`
}

// AnnouncementListResponse defines model for AnnouncementListResponse.
type AnnouncementListResponse struct {
	Announcements []AnnouncementSummary `json:"announcements"`
}

// AnnouncementSummary `GET /api/v1/support/announcements` のレスポンス要素 (FEATURE_SPEC §4)。
// expires_at / body はクライアントに露出させない。
type AnnouncementSummary struct {
	AnnouncementID int64     `json:"announcement_id"`
	PublishedAt    time.Time `json:"published_at"`
	Title          string    `json:"title"`

	// Type お知らせ種別 (FEATURE_SPEC §2)。
	Type AnnouncementType `json:"type"`
}

// AnnouncementType お知らせ種別 (FEATURE_SPEC §2)。
type AnnouncementType string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// SubmitInquiryRequest `POST /api/v1/inquiries` の入力 (FEATURE_SPEC §7.1)。
type SubmitInquiryRequest struct {
	Body string `json:"body"`

	// ReplyEmail 返信先メールアドレス (validate は usecase 層が担う)
	ReplyEmail string `json:"reply_email"`
	Title      string `json:"title"`
}

// SubmitInquiryResponse `POST /api/v1/inquiries` の出力。
type SubmitInquiryResponse struct {
	InquiryID int64 `json:"inquiry_id"`
}

// AnnouncementIdPath defines model for AnnouncementIdPath.
type AnnouncementIdPath = int64

// LangQuery defines model for LangQuery.
type LangQuery = string

// ListAnnouncementsParams defines parameters for ListAnnouncements.
type ListAnnouncementsParams struct {
	// Lang 取得言語 (FEATURE_SPEC §3)。許容値は domain.SupportedLangs と同期する
	// (drift 検知は本ファイルでは行わず application 層で `IsSupportedLang` が担う)。
	Lang LangQuery `form:"lang" json:"lang"`
}

// GetAnnouncementParams defines parameters for GetAnnouncement.
type GetAnnouncementParams struct {
	// Lang 取得言語 (FEATURE_SPEC §3)。許容値は domain.SupportedLangs と同期する
	// (drift 検知は本ファイルでは行わず application 層で `IsSupportedLang` が担う)。
	Lang LangQuery `form:"lang" json:"lang"`
}

// SubmitInquiryJSONRequestBody defines body for SubmitInquiry for application/json ContentType.
type SubmitInquiryJSONRequestBody = SubmitInquiryRequest
