#!/usr/bin/env python3
"""overload-party-support の型コード生成スクリプト。

data/models.yaml を読み、各セクションの target / targets 指定に従って
internal/domain/ (package domain) または packages/api-support/ (package apisupport)
に Go の型を出力する。同じ JSON 形状を要求する型を両層に出力したい場合は
targets: [domain, wire] で複数指定できる。

実行: python3 scripts/generate_types.py
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.stderr.write("error: PyYAML is required (pip install pyyaml)\n")
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_YAML = REPO_ROOT / "data" / "models.yaml"

GENERATED_HEADER_GO = "// Code generated by scripts/generate_types.py; DO NOT EDIT."

TARGETS: dict[str, tuple[Path, str]] = {
    "domain": (REPO_ROOT / "internal" / "domain", "domain"),
    "wire": (REPO_ROOT / "packages" / "api-support", "apisupport"),
}


def _go_type_needs_import(type_str: str) -> set[str]:
    """型文字列から推論される import path の集合を返す。"""
    imports: set[str] = set()
    if "time.Time" in type_str or "time." in type_str:
        imports.add("time")
    if "json.RawMessage" in type_str:
        imports.add("encoding/json")
    if "civil.Date" in type_str or "civil." in type_str:
        imports.add("cloud.google.com/go/civil")
    return imports


def _emit_go_import_block(imports: set[str]) -> list[str]:
    """import path の集合を Go の import ブロック行に整形する。"""
    if not imports:
        return []
    std = sorted(i for i in imports if "." not in i.split("/")[0])
    ext = sorted(i for i in imports if "." in i.split("/")[0])
    lines = ["import ("]
    for imp in std:
        lines.append(f'\t"{imp}"')
    if std and ext:
        lines.append("")
    for imp in ext:
        lines.append(f'\t"{imp}"')
    lines.append(")")
    lines.append("")
    return lines


def _emit_go_constants(constants: list[dict]) -> list[str]:
    """定数定義ブロックを const ( ... ) 行に整形する。"""
    lines: list[str] = []
    for const_block in constants:
        const_type = const_block.get("type", "string")
        values = const_block.get("values", [])
        if not values:
            continue
        lines.append("const (")
        for v in values:
            name = v["name"]
            value = v["value"]
            if const_type == "string":
                lines.append(f'\t{name} = "{value}"')
            else:
                lines.append(f"\t{name} = {value}")
        lines.append(")")
        lines.append("")
    return lines


def _emit_go_type(td: dict) -> list[str]:
    """型定義 1 件を Go の type ... struct { ... } 行に整形する。"""
    lines: list[str] = []
    if td.get("comment"):
        for cl in str(td["comment"]).rstrip("\n").splitlines():
            lines.append(f"// {cl}" if cl else "//")
    lines.append(f"type {td['name']} struct {{")

    fields = td.get("fields", [])
    if fields:
        max_name_len = max(len(f["name"]) for f in fields)
        max_type_len = max(len(str(f["type"])) for f in fields)

    for field in fields:
        fname = field["name"]
        ftype = str(field["type"])
        tags: list[str] = []
        if "json" in field:
            tags.append(f'json:"{field["json"]}"')
        tag_str = " ".join(tags)

        name_pad = " " * (max_name_len - len(fname) + 1)
        type_pad = " " * (max_type_len - len(ftype) + 1)

        if tag_str:
            line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_str}`"
        else:
            line = f"\t{fname}{name_pad}{ftype}"

        if field.get("comment"):
            line += f" // {field['comment']}"
        lines.append(line)

    lines.append("}")
    lines.append("")
    return lines


def _generate_go_file(file_def: dict, target: str) -> None:
    """1 セクション分の型を指定 target のパッケージにファイル出力する。"""
    if target not in TARGETS:
        sys.stderr.write(f"error: unknown target {target!r} in section {file_def.get('name')!r}\n")
        sys.exit(1)
    out_dir, pkg_name = TARGETS[target]

    lines: list[str] = [GENERATED_HEADER_GO, "", f"package {pkg_name}", ""]

    imports = set(file_def.get("imports", []))
    for td in file_def.get("types", []):
        for field in td.get("fields", []):
            imports |= _go_type_needs_import(str(field["type"]))

    lines.extend(_emit_go_import_block(imports))

    constants = file_def.get("constants", [])
    lines.extend(_emit_go_constants(constants))

    for td in file_def.get("types", []):
        lines.extend(_emit_go_type(td))

    out_path = out_dir / f"{file_def['name']}_gen.go"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


def _resolve_targets(file_def: dict) -> list[str]:
    """セクションの `target` / `targets` 指定を出力 target 名のリストに正規化する。"""
    if "targets" in file_def and "target" in file_def:
        sys.stderr.write(
            f"error: section {file_def.get('name')!r} sets both `target` and `targets`\n"
        )
        sys.exit(1)
    if "targets" in file_def:
        ts = file_def["targets"]
        if not isinstance(ts, list) or not ts:
            sys.stderr.write(
                f"error: section {file_def.get('name')!r} `targets` must be a non-empty list\n"
            )
            sys.exit(1)
        return list(ts)
    if "target" in file_def:
        return [file_def["target"]]
    sys.stderr.write(
        f"error: section {file_def.get('name')!r} has no `target` or `targets`\n"
    )
    sys.exit(1)


def main() -> int:
    """エントリポイント。models.yaml を読み込んで全セクションを生成する。"""
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    sections = data.get("files")
    if not sections:
        sys.stderr.write("error: data/models.yaml has no `files:` section\n")
        return 1

    for file_def in sections:
        for target in _resolve_targets(file_def):
            _generate_go_file(file_def, target)

    return 0


if __name__ == "__main__":
    sys.exit(main())
