// Code generated by scripts/generate_types.py; DO NOT EDIT.

package domain

const (
	TypeInfo = "info"
	TypeMaintenance = "maintenance"
	TypeEvent = "event"
	TypeUpdate = "update"
	LangJa = "ja"
	LangEn = "en"
	StateDraft = "draft"
	StateScheduled = "scheduled"
	StatePublished = "published"
	StateExpired = "expired"
)

